version: "3.9"
services:
  proxy:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
    ports:
      - "5173:5173"
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-volume:/var/lib/mysql
  db-test:
    build: ./docker/mysql
    ports:
      - 3307:3306
volumes:
  db-volume:
